name: Check CT jasmin-ref implementation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux, X64, amd64-main]
    strategy:
      matrix:
        directory:
          - wots
    steps:
      - uses: actions/checkout@v4
      - name: Generate preprocessed files
        run:
          JASMIN=$(which_jasminc) make -C test/${{ matrix.directory }} jpp_files
      - name: Check CT
        run:
          JASMIN=$(which_jasminc) make -C test/${{ matrix.directory }} checkct
